export type Language = "zh" | "en" | "de" | "fr";

export const LANGUAGES: { id: Language; label: string }[] = [
  { id: "zh", label: "中文" },
  { id: "en", label: "English" },
  { id: "de", label: "Deutsch" },
  { id: "fr", label: "Français" },
];

const copy = {
  zh: {
    language: "语言", loading: "正在准备花材…", brand: "数字花艺工作室", stems: "枝花材", undo: "撤销", redo: "重做", startOver: "重新开始", finish: "完成花束", waves: "海浪", breeze: "海风", rain: "小雨", birds: "鸟鸣", fireplace: "壁炉", cicadas: "蝉鸣",
    step: "01 · 挑选 · 摆放 · 感受", headline: "在空间中自由创作。", intro: "点击花材即可放入合适的位置，也可以拖动进行细致调整。",
    flowers: "花材", containers: "容器", library: "花材与容器", main: "主花", accents: "配花", foliage: "叶材", chooseFlowers: "今天想搭配什么花？", chooseFlowersHint: "选择花材，放进你的作品。", chooseContainer: "选择容器", chooseContainerHint: "选择花瓶、花束包装，或从灵感花束开始。",
    added: "已添加", preorder: "即将开放", studioOnly: "仅供创作", vase: "花瓶", bouquets: "花束包装", imagination: "灵感花束", adjustContainer: "调整容器", containerSize: "容器大小", containerColor: "容器颜色", opacity: "透明度", stemsTab: "枝", stem: "枝", adjust: "调整花材", adjustHint: "点击花材可调整高度、大小、角度和颜色。", tools: "工具", tapToAdjust: "已放入花束；点花头可调整。", stemToAdjust: "正在调整", stemHeight: "枝条高度", flowerSize: "花头大小", leafSize: "叶材大小", lean: "倾斜角度", flowerColor: "花色", removeStem: "移除此枝", done: "完成调整",
    morningLight: "晨光", warmth: "冷暖", balanced: "自然", cool: "冷色", warm: "暖色", direction: "方向", turnLeft: "向左", turnRight: "向右", wind: "微风", windStrength: "风力", ambience: "环境音", volume: "音量", mute: "静音", unmute: "取消静音", rotateVase: "旋转花瓶", rotateHint: "左右拖动旋转，上下拖动倾斜，按住 Shift 拖动可翻转。", rotateTouchHint: "在空白处滑动可旋转、倾斜花束；翻转可用下方滑杆。", tilt: "倾斜", turn: "旋转", roll: "翻转", resetRotation: "重置视角", placeHint: "选择花材并点击画布放置。", placePrompt: "点击花材开始创作", dragPrompt: "拖动花材到画布中 · Esc 取消",
    sendEyebrow: "赠你一束花", sendTitle: "把花束送给重要的人。", sendHint: "写下一段祝福，生成专属明信片分享给朋友。", to: "收件人", message: "祝福语", from: "署名", recipientPlaceholder: "想送给谁？", messagePlaceholder: "愿你的每一天，都有花开。", senderPlaceholder: "你的名字", privateLink: "专属分享链接", copyLink: "复制链接", shareDirectly: "直接分享", download: "下载明信片", saveToPhotos: "保存到相册", longPressToSave: "长按明信片图片，选择“保存图片”即可存入相册。", createLink: "生成分享链接", createAnother: "再生成一个链接", creating: "正在生成…", back: "返回编辑", postcardTitle: "Bloomroom · 一份鲜花心意", defaultMessage: "愿你的每一天，都有花开。", close: "返回编辑", credits: "3D 模型作者与来源", postcardKicker: "一点心意，送给你", openBouquet: "在工作室中查看这束花", createBouquet: "创作自己的花束",
    restored: "已从分享链接恢复花束。", full: "花束最多可搭配 24 枝，请先移除一枝。", loadingModels: "花材模型仍在载入，请稍后再试。", addFirst: "请先添加一枝花材。", captureError: "无法生成花束预览，请重试。", saved: "已复制明信片链接。", shareFallback: "此设备无法打开分享菜单，链接已复制。", copyError: "复制失败，请选中上方链接手动复制。", savingError: "无法保存明信片，请重试。", imageLoading: "明信片仍在生成，请稍后重试。", drawError: "无法生成明信片，请重试。",    countLabel: "枝花材", of: "/", toName: "送给", fromName: "来自", backdrop: "背景",
    login: "登录", signup: "注册", logout: "退出登录", myGarden: "我的花房", saveDraft: "保存草稿", savingDraft: "正在保存…", draftSaved: "草稿已保存", draftUpdated: "草稿已更新", drafts: "草稿箱", sentPostcards: "送出的明信片", noDrafts: "暂无草稿，快去创作一束花吧。", noSentPostcards: "暂无送出的明信片。", continueEdit: "继续编辑", remixCopy: "基于此创作新花束", rename: "重命名", deleteAction: "删除", confirmDelete: "确定删除这个草稿吗？", viewGift: "查看礼物", authNotice: "请记住用户名和密码，暂不支持找回。", loginToSaveHint: "登录后将为您自动保存到草稿箱。请记住用户名和密码，暂不支持找回。", usernameLabel: "用户名", passwordLabel: "密码", usernameHint: "3–32 位字母、数字或下划线", passwordHint: "输入密码", confirmPasswordLabel: "确认密码", confirmPasswordHint: "再次输入密码", passwordMismatch: "两次输入的密码不一致", showPassword: "查看密码", hidePassword: "隐藏密码", alreadyHaveAccount: "已有账号？去登录", needAccount: "还没有账号？免费注册", conflictNotice: "该草稿在其他设备已被修改，已为您保存为新草稿以保留最新创作。", untitledBouquet: "未命名花束", loginSuccess: "登录成功", signupSuccess: "注册成功并已登录", logoutSuccess: "已退出登录", draftLoaded: "已载入草稿",
    loadBouquetError: "无法载入花束，请重试。若旧草稿数据已丢失，可从送出的明信片重新创作。",
    recordVoice: "录一句祝福（可选）", recordingVoice: "正在录音…", stopRecording: "停止录音", rerecordVoice: "重新录制", deleteVoice: "删除语音", playVoice: "试听", pauseVoice: "暂停", listenToVoice: "听听 TA 的声音", micDenied: "无法访问麦克风。请检查权限后重试，或直接发送明信片。", micUnsupported: "当前设备不支持录音，您仍可发送普通明信片。", audioTooLarge: "录音文件超过 2MB 限制，请重新录制。", audioPlayError: "语音加载失败，可稍后重试。", voiceHint: "最长录制 30 秒，支持试听和重录。",
    aiReading: "花间照见", aiReadingHint: "从花的姿态与色彩，读一读此刻的你。", aiReadingDisclaimer: "创作式心理联想", generateReading: "生成花艺解读", generatingReading: "正在细细观赏你的花束…", readingTitle: "花境名", readingComposition: "作品解读", readingReflection: "心境联想", readingBody: "心理联想", readingPunchline: "灵感花签", readingQuote: "一句花签", copyReading: "复制文案", readingCopied: "解读已复制到剪贴板", saveReadingCard: "保存解读卡", savingReadingCard: "正在保存…", regenerateReading: "重新解读", outdatedReadingNotice: "作品已有修改，此为上一版本解读", readingError: "生成解读失败，请重试。",
    gallery: "花廊", galleryTitle: "花廊", gallerySubtitle: "漫步花间，遇见大家的灵感与心意。", latest: "最新", popular: "最受喜欢", likeAction: "喜欢", likedAction: "已喜欢", visibilityLabel: "公开展示", publicBadge: "公开", privateBadge: "私有", setPublic: "设为公开", setPrivate: "设为私有", galleryNotice: "完成后自动展示在花廊", galleryNoticePrivate: "当前设为仅自己可见", anonymousFlorist: "匿名花友", view3dBouquet: "查看 3D 花束", remixCreation: "以此为基础创作", myCreations: "我的作品", noCreations: "暂无作品，插一束花分享到花廊吧。", saveToGallery: "保存作品到花廊", savingToGallery: "正在保存作品…", savedToGallery: "作品已收录到花廊", retrySave: "重试", loadMore: "加载更多", loadingMore: "正在加载…", allLoaded: "已加载全部作品", emptyGallery: "花廊空空如也，快来留下第一束花吧。", confirmDeleteCreation: "确定删除这个作品吗？", visibilityUpdated: "可见性已更新", creationDeleted: "作品已删除",
    backdropNames: { linen: "米麻", limestone: "石灰", charcoal: "炭灰", forest: "墨绿" },
    vaseNames: { classic: "柔和陶瓶", bud: "小口花瓶", bowl: "宽口花钵", footed: "高脚花器", mug: "茶杯花器", paper: "牛皮纸包装", canvas: "纸包与丝带", naked: "自然裸枝" },
    vaseNotes: { classic: "圆润的工作室陶瓶", bud: "纤细安静的轮廓", bowl: "低矮而舒展", footed: "带一点仪式感", mug: "日常茶杯花器", paper: "温暖的折叠牛皮纸", canvas: "折纸包装并系上蝴蝶结", naked: "简单扎束的裸枝" },
    presets: { "first-light": "晨光初绽", "meadow-air": "旷野微风", "cloud-study": "云朵练习" },
    flowerNames: { rose: "玫瑰", tulip: "郁金香", daisy: "雏菊", poppy: "虞美人", peony: "芍药", "blue-poppy": "蓝罂粟", eucalyptus: "银圆尤加利", gerbera: "非洲菊", chrysanthemum: "菊花", hydrangea: "绣球花", "lily-of-the-valley": "铃兰", fern: "蕨叶", "seeded-eucalyptus": "果荚尤加利", sunflower: "向日葵", orchid: "蝴蝶兰", "calla-lily": "马蹄莲", carnation: "康乃馨", lily: "百合", lotus: "荷花", anemone: "银莲花", chamomile: "洋甘菊", delphinium: "飞燕草", snowdrop: "雪滴花", lavender: "薰衣草", ivy: "常春藤", monstera: "龟背竹叶", "ranunculus": "洋牡丹", "narcissus": "水仙", "dahlia": "大丽花", "amaryllis": "朱顶红", "astrantia": "大星芹", "eryngium": "刺芹", "pine-cone": "松果" },
    colors: { "Dusty rose": "灰粉玫瑰色", "Velvet red": "绒红", "Ivory cream": "象牙奶油色", "Butter yellow": "奶油黄", Apricot: "杏色", Mauve: "藕紫", Blush: "浅粉", "Tulip red": "郁金香红", "Golden yellow": "金黄", White: "白色", Violet: "紫罗兰色", "Cream white": "乳白", "Golden daisy": "金色雏菊", Coral: "珊瑚色", Scarlet: "猩红", Orange: "橙色", "Blush pink": "柔粉", "Deep red": "深红", "Himalayan blue": "喜马拉雅蓝", "Violet blue": "蓝紫色", "Warm orange": "暖橙", Red: "红色", Pink: "粉色", Yellow: "黄色", Golden: "金色", Lavender: "薰衣草紫", "Misty lilac": "雾紫", "Garden blue": "花园蓝", "Rose pink": "玫瑰粉", Ivory: "象牙白", "Soft pink": "柔粉", Terracotta: "陶土色", "Lemon cream": "柠檬奶油色", "Blush mauve": "浅藕紫", "Pure white": "纯白", "Deep violet": "深紫", "Snow white": "雪白", Sunshine: "阳光黄", "Dark plum": "深李子色", "Stargazer pink": "粉色香水百合", "Tiger orange": "虎纹橙", "Deep rose": "深玫瑰色", "Cornflower blue": "矢车菊蓝", "Classic purple": "经典紫", "Rose lavender": "玫瑰薰衣草色", "White spike": "白色花穗", "Bronze red": "古铜红", Butter: "奶油黄", "Cobalt blue": "钴蓝", Crimson: "深红", "Ivory peach": "象牙蜜桃色", "Violet purple": "紫罗兰", "Paper white": "纸白", Kraft: "牛皮纸色", Pearl: "珍珠白", Stone: "石色", Sage: "鼠尾草绿", Forest: "森林绿", Porcelain: "瓷白", Charcoal: "炭灰" },
    categoryName: { main: "主花", filler: "配花", foliage: "叶材" },
  },
  en: {
    language: "Language", loading: "Preparing the flowers…", brand: "Digital Flower Studio", stems: "stems", undo: "Undo", redo: "Redo", startOver: "Start over", finish: "Finish bouquet", waves: "Waves", breeze: "Breeze", rain: "Rain", birds: "Birds", fireplace: "Fireplace", cicadas: "Cicadas",
    step: "01 · Pick · Place · Feel", headline: "Arrange in space.", intro: "Click to add a flower in a balanced spot, or drag it for precise placement.",
    flowers: "Flowers", containers: "Containers", library: "Flower and container library", main: "Main flowers", accents: "Accents", foliage: "Foliage", chooseFlowers: "What will you arrange today?", chooseFlowersHint: "Choose a flower, then place it in your arrangement.", chooseContainer: "Choose a container", chooseContainerHint: "Choose a vase, wrap, or start from a bouquet.",
    added: "Added", preorder: "preorder", studioOnly: "studio only", vase: "Vases", bouquets: "Bouquets", imagination: "Imagination", adjustContainer: "Adjust container", containerSize: "Container size", containerColor: "Container color", opacity: "Opacity", stemsTab: "stems", stem: "stem", adjust: "Adjust flowers", adjustHint: "Click a flower to edit its height, size, angle, and color.", tools: "Tools", tapToAdjust: "Added. Tap a flower to adjust it.", stemToAdjust: "Flower to adjust", stemHeight: "Stem height", flowerSize: "Flower size", leafSize: "Leaf size", lean: "Lean / angle", flowerColor: "Flower color", removeStem: "Remove this stem", done: "Done adjusting",
    morningLight: "Morning light", warmth: "Warmth", balanced: "Balanced", cool: "Cool", warm: "Warm", direction: "Direction", turnLeft: "Turn left", turnRight: "Turn right", wind: "Wind", windStrength: "Wind strength", ambience: "Ambience", volume: "Volume", mute: "Mute ambience", unmute: "Unmute ambience", rotateVase: "Rotate vase", rotateHint: "Drag left/right to turn, up/down to tilt. Hold Shift to roll.", rotateTouchHint: "Swipe empty space to turn and tilt. Use the slider below to roll.", tilt: "Tilt", turn: "Turn", roll: "Roll", resetRotation: "Reset rotation", placeHint: "Pick a flower and click in the room to place it.", placePrompt: "Choose a flower to begin", dragPrompt: "Drag a flower into the room · Esc to cancel",
    sendEyebrow: "A gift of flowers", sendTitle: "Send your bouquet.", sendHint: "Write a note, then make a personal postcard to share.", to: "To", message: "Message", from: "From", recipientPlaceholder: "Someone you love", messagePlaceholder: "May your day bloom in its own way.", senderPlaceholder: "Your name", privateLink: "Your private postcard link", copyLink: "Copy link", shareDirectly: "Share now", download: "Download postcard", saveToPhotos: "Save to Photos", longPressToSave: "Touch and hold the postcard, then choose Save Image.", createLink: "Create share link", createAnother: "Create another link", creating: "Creating…", back: "Back to editing", postcardTitle: "Bloomroom · A gift of flowers", defaultMessage: "May your day bloom in its own way.", close: "Back to editing", credits: "3D artists & credits", postcardKicker: "A little something for you", openBouquet: "See this bouquet in the studio", createBouquet: "Make your own bouquet",
    restored: "Bouquet restored from a shared link.", full: "Your arrangement holds 24 stems. Remove one to make room.", loadingModels: "Some 3D previews are still rendering. Try again in a moment.", addFirst: "Add a stem to your arrangement first.", captureError: "Could not capture the bouquet. Please try again.", saved: "Postcard link copied.", shareFallback: "Sharing is unavailable here; the link was copied.", copyError: "Copy failed. Select the link above to copy it manually.", savingError: "Could not save this postcard. Please try again.", imageLoading: "Image is still rendering. Try once more.", drawError: "Could not draw the postcard. Try again.", countLabel: "stems", of: "/", toName: "To", fromName: "From", backdrop: "Backdrop",
    login: "Log in", signup: "Sign up", logout: "Log out", myGarden: "My Garden", saveDraft: "Save draft", savingDraft: "Saving…", draftSaved: "Draft saved", draftUpdated: "Draft updated", drafts: "Drafts", sentPostcards: "Sent postcards", noDrafts: "No drafts yet. Arrange a bouquet to save your first draft.", noSentPostcards: "No sent postcards yet.", continueEdit: "Continue editing", remixCopy: "Remix into new bouquet", rename: "Rename", deleteAction: "Delete", confirmDelete: "Delete this draft?", viewGift: "View postcard", authNotice: "Please remember your username and password, recovery is not supported.", loginToSaveHint: "Log in to save this bouquet to your drafts. Please remember your credentials as recovery is not supported.", usernameLabel: "Username", passwordLabel: "Password", usernameHint: "3–32 letters, numbers, or underscores", passwordHint: "Enter your password", confirmPasswordLabel: "Confirm password", confirmPasswordHint: "Enter your password again", passwordMismatch: "Passwords do not match", showPassword: "Show password", hidePassword: "Hide password", alreadyHaveAccount: "Already have an account? Log in", needAccount: "Don't have an account? Sign up", conflictNotice: "This draft was modified on another device. Saved as a new draft to keep your changes.", untitledBouquet: "Untitled Bouquet", loginSuccess: "Logged in successfully", signupSuccess: "Account created and logged in", logoutSuccess: "Logged out", draftLoaded: "Draft loaded into studio",
    loadBouquetError: "Could not load this bouquet. Try again, or restore an old draft from a sent postcard.",
    recordVoice: "Record voice note (optional)", recordingVoice: "Recording…", stopRecording: "Stop recording", rerecordVoice: "Re-record", deleteVoice: "Delete voice", playVoice: "Preview", pauseVoice: "Pause", listenToVoice: "Listen to their voice", micDenied: "Could not access microphone. Please check permissions or send without audio.", micUnsupported: "Audio recording is not supported on this device. You can still send a text postcard.", audioTooLarge: "Audio file exceeds 2MB limit, please re-record.", audioPlayError: "Could not load voice greeting. Please try again later.", voiceHint: "Up to 30 seconds, supports preview and re-recording.",
    aiReading: "Floral Reflection", aiReadingHint: "A poetic reading of this moment through posture and color.", aiReadingDisclaimer: "A creative psychological reflection", generateReading: "Generate Reflection", generatingReading: "Observing your arrangement…", readingTitle: "Title", readingComposition: "Composition", readingReflection: "Reflection", readingBody: "Reflection", readingPunchline: "Punchline", readingQuote: "Botanical Verse", copyReading: "Copy text", readingCopied: "Reflection copied to clipboard", saveReadingCard: "Save card", savingReadingCard: "Saving card…", regenerateReading: "Re-interpret", outdatedReadingNotice: "The arrangement has changed; showing previous reflection", readingError: "Could not generate reflection. Please retry.",
    gallery: "Gallery", galleryTitle: "Floral Gallery", gallerySubtitle: "Wander through bouquets created by florists around the world.", latest: "Latest", popular: "Most Popular", likeAction: "Like", likedAction: "Liked", visibilityLabel: "Public Gallery", publicBadge: "Public", privateBadge: "Private", setPublic: "Make Public", setPrivate: "Make Private", galleryNotice: "Completed bouquets appear in the gallery automatically", galleryNoticePrivate: "Currently set to private (only visible to you)", anonymousFlorist: "Anonymous Florist", view3dBouquet: "View 3D Bouquet", remixCreation: "Remix This Bouquet", myCreations: "My Works", noCreations: "No works yet. Arrange a bouquet to share in the gallery.", saveToGallery: "Save to Gallery", savingToGallery: "Saving to gallery…", savedToGallery: "Artwork added to gallery", retrySave: "Retry", loadMore: "Load more", loadingMore: "Loading more…", allLoaded: "All works loaded", emptyGallery: "The gallery is empty. Be the first to share a bouquet!", confirmDeleteCreation: "Delete this artwork?", visibilityUpdated: "Visibility updated", creationDeleted: "Artwork deleted",
    backdropNames: { linen: "Linen", limestone: "Limestone", charcoal: "Charcoal", forest: "Forest" },
    vaseNames: { classic: "Soft ceramic", bud: "Bud vase", bowl: "Wide bowl", footed: "Footed urn", mug: "Tea cup", paper: "Paper wrap", canvas: "Paper + ribbon", naked: "Naked stems" },
    vaseNotes: { classic: "Rounded studio vase", bud: "A quiet, narrow silhouette", bowl: "Low and generous", footed: "A little ceremony", mug: "An everyday vessel", paper: "Warm folded kraft paper", canvas: "Folded paper tied with a bow", naked: "Bare stems, simply tied" },
    presets: { "first-light": "First light", "meadow-air": "Meadow air", "cloud-study": "Cloud study" },
    flowerNames: { rose: "Garden rose", tulip: "Tulip", daisy: "Daisy", poppy: "Poppy", peony: "Peony", "blue-poppy": "Blue poppy", eucalyptus: "Silver dollar eucalyptus", gerbera: "Gerbera", chrysanthemum: "Chrysanthemum", hydrangea: "Hydrangea", "lily-of-the-valley": "Lily of the valley", fern: "Fern greenery", "seeded-eucalyptus": "Eucalyptus sprig", sunflower: "Sunflower", orchid: "Orchid", "calla-lily": "Calla lily", carnation: "Carnation", lily: "Lily", lotus: "Lotus", anemone: "Anemone", chamomile: "Chamomile", delphinium: "Delphinium", snowdrop: "Snowdrop", lavender: "Lavender", ivy: "Ivy sprig", monstera: "Monstera leaf", "ranunculus": "Ranunculus", "narcissus": "Narcissus", "dahlia": "Dahlia", "amaryllis": "Amaryllis", "astrantia": "Astrantia", "eryngium": "Sea holly", "pine-cone": "Pine cone" },
    colors: {}, categoryName: { main: "Main flowers", filler: "Accents", foliage: "Foliage" },
  },
  de: {
    language: "Sprache", loading: "Blumen werden vorbereitet …", brand: "Digitales Blumenatelier", stems: "Stiele", undo: "Rückgängig", redo: "Wiederholen", startOver: "Neu beginnen", finish: "Strauß fertigstellen", waves: "Wellen", breeze: "Brise", rain: "Regen", birds: "Vögel", fireplace: "Kaminfeuer", cicadas: "Zikaden",
    step: "01 · Wählen · Platzieren · Gestalten", headline: "Gestalte im Raum.", intro: "Klicke, um eine Blume passend zu platzieren, oder ziehe sie für eine genaue Position.",
    flowers: "Blumen", containers: "Gefäße", library: "Blumen und Gefäße", main: "Hauptblumen", accents: "Beiwerk", foliage: "Grün", chooseFlowers: "Was möchtest du heute arrangieren?", chooseFlowersHint: "Wähle eine Blume und platziere sie im Arrangement.", chooseContainer: "Gefäß wählen", chooseContainerHint: "Wähle eine Vase, eine Verpackung oder ein Arrangement als Inspiration.",
    added: "Hinzugefügt", preorder: "Vorbestellung", studioOnly: "nur Inspiration", vase: "Vasen", bouquets: "Sträuße", imagination: "Inspiration", adjustContainer: "Gefäß anpassen", containerSize: "Gefäßgröße", containerColor: "Gefäßfarbe", opacity: "Deckkraft", stemsTab: "Stiele", stem: "Stiel", adjust: "Blumen anpassen", adjustHint: "Klicke auf eine Blume, um Höhe, Größe, Winkel und Farbe anzupassen.", tools: "Werkzeuge", tapToAdjust: "Hinzugefügt. Tippe zum Anpassen auf eine Blume.", stemToAdjust: "Blume auswählen", stemHeight: "Stiellänge", flowerSize: "Blütengröße", leafSize: "Blattgröße", lean: "Neigung", flowerColor: "Blütenfarbe", removeStem: "Stiel entfernen", done: "Fertig",
    morningLight: "Morgenlicht", warmth: "Wärme", balanced: "Ausgeglichen", cool: "Kühl", warm: "Warm", direction: "Richtung", turnLeft: "Nach links", turnRight: "Nach rechts", wind: "Wind", windStrength: "Windstärke", ambience: "Atmosphäre", volume: "Lautstärke", mute: "Ton ausschalten", unmute: "Ton einschalten", rotateVase: "Vase drehen", rotateHint: "Links/rechts ziehen zum Drehen, hoch/runter zum Neigen. Mit Shift rollen.", rotateTouchHint: "Im freien Bereich wischen zum Drehen und Neigen. Zum Rollen den Regler unten nutzen.", tilt: "Neigen", turn: "Drehen", roll: "Rollen", resetRotation: "Ansicht zurücksetzen", placeHint: "Wähle eine Blume und klicke in den Raum.", placePrompt: "Wähle eine Blume aus", dragPrompt: "Ziehe eine Blume in den Raum · Esc zum Abbrechen",
    sendEyebrow: "Ein Blumengruß", sendTitle: "Verschenke deinen Strauß.", sendHint: "Schreibe eine Nachricht und erstelle eine persönliche Postkarte zum Teilen.", to: "An", message: "Nachricht", from: "Von", recipientPlaceholder: "Für einen lieben Menschen", messagePlaceholder: "Möge jeder deiner Tage erblühen.", senderPlaceholder: "Dein Name", privateLink: "Dein persönlicher Postkartenlink", copyLink: "Link kopieren", shareDirectly: "Direkt teilen", download: "Postkarte herunterladen", saveToPhotos: "In Fotos speichern", longPressToSave: "Postkarte gedrückt halten und „Bild speichern“ wählen.", createLink: "Teilungslink erstellen", createAnother: "Weiteren Link erstellen", creating: "Wird erstellt …", back: "Zurück zum Bearbeiten", postcardTitle: "Bloomroom · Ein Blumengruß", defaultMessage: "Möge jeder deiner Tage erblühen.", close: "Zurück zum Bearbeiten", credits: "3D Modelle · Credits", postcardKicker: "Ein kleiner Gruß für dich", openBouquet: "Diesen Strauß im Atelier ansehen", createBouquet: "Eigenen Strauß gestalten",
    restored: "Strauß aus dem geteilten Link wiederhergestellt.", full: "Dein Arrangement fasst 24 Stiele. Entferne einen, um Platz zu schaffen.", loadingModels: "Einige 3D-Modelle werden noch geladen. Bitte gleich erneut versuchen.", addFirst: "Füge zuerst einen Stiel hinzu.", captureError: "Der Strauß konnte nicht aufgenommen werden. Bitte erneut versuchen.", saved: "Postkartenlink kopiert.", shareFallback: "Teilen ist hier nicht verfügbar; der Link wurde kopiert.", copyError: "Kopieren fehlgeschlagen. Wähle den Link oben zum manuellen Kopieren aus.", savingError: "Postkarte konnte nicht gespeichert werden. Bitte erneut versuchen.", imageLoading: "Das Bild wird noch gerendert. Bitte erneut versuchen.", drawError: "Postkarte konnte nicht erstellt werden. Bitte erneut versuchen.", countLabel: "Stiele", of: "/", toName: "An", fromName: "Von", backdrop: "Hintergrund",
    login: "Anmelden", signup: "Registrieren", logout: "Abmelden", myGarden: "Mein Garten", saveDraft: "Entwurf speichern", savingDraft: "Wird gespeichert…", draftSaved: "Entwurf gespeichert", draftUpdated: "Entwurf aktualisiert", drafts: "Entwürfe", sentPostcards: "Gesendete Postkarten", noDrafts: "Noch keine Entwürfe. Gestalte einen Strauß und speichere ihn hier.", noSentPostcards: "Noch keine Postkarten versendet.", continueEdit: "Weiterbearbeiten", remixCopy: "Neuen Strauß daraus erstellen", rename: "Umbenennen", deleteAction: "Löschen", confirmDelete: "Diesen Entwurf löschen?", viewGift: "Postkarte ansehen", authNotice: "Bitte merke dir Benutzername und Passwort, Wiederherstellung wird nicht unterstützt.", loginToSaveHint: "Melde dich an, um den Entwurf zu speichern. Bitte Zugangsdaten merken (keine Wiederherstellung).", usernameLabel: "Benutzername", passwordLabel: "Passwort", usernameHint: "3–32 Buchstaben, Zahlen oder Unterstriche", passwordHint: "Passwort eingeben", confirmPasswordLabel: "Passwort bestätigen", confirmPasswordHint: "Passwort erneut eingeben", passwordMismatch: "Die Passwörter stimmen nicht überein", showPassword: "Passwort anzeigen", hidePassword: "Passwort verbergen", alreadyHaveAccount: "Bereits registriert? Anmelden", needAccount: "Noch kein Konto? Registrieren", conflictNotice: "Dieser Entwurf wurde auf einem anderen Gerät geändert. Als neuer Entwurf gespeichert.", untitledBouquet: "Unbenannter Strauß", loginSuccess: "Erfolgreich angemeldet", signupSuccess: "Konto erstellt und angemeldet", logoutSuccess: "Erfolgreich abgemeldet", draftLoaded: "Entwurf ins Atelier geladen",
    loadBouquetError: "Dieser Strauß konnte nicht geladen werden. Versuche es erneut oder stelle ihn aus einer gesendeten Postkarte wieder her.",
    recordVoice: "Sprachnachricht aufnehmen (optional)", recordingVoice: "Aufnahme läuft …", stopRecording: "Aufnahme stoppen", rerecordVoice: "Erneut aufnehmen", deleteVoice: "Sprachnachricht löschen", playVoice: "Anhören", pauseVoice: "Pause", listenToVoice: "Sprachnachricht anhören", micDenied: "Kein Zugriff auf das Mikrofon. Bitte Berechtigungen prüfen oder ohne Ton senden.", micUnsupported: "Audioaufnahme wird auf diesem Gerät nicht unterstützt.", audioTooLarge: "Die Audiodatei überschreitet 2 MB, bitte neu aufnehmen.", audioPlayError: "Sprachnachricht konnte nicht geladen werden.", voiceHint: "Bis zu 30 Sekunden, Vorschau und erneute Aufnahme möglich.",
    aiReading: "Blumenbetrachtung", aiReadingHint: "Ergründen Sie den Augenblick durch Haltung und Farbe.", aiReadingDisclaimer: "Kreative psychologische Betrachtung", generateReading: "Betrachtung erstellen", generatingReading: "Blumenwerk wird betrachtet…", readingTitle: "Titel", readingComposition: "Komposition", readingReflection: "Resonanz", readingBody: "Betrachtung", readingPunchline: "Pointe", readingQuote: "Blumengruß", copyReading: "Text kopieren", readingCopied: "In Zwischenablage kopiert", saveReadingCard: "Karte speichern", savingReadingCard: "Wird gespeichert…", regenerateReading: "Neu betrachten", outdatedReadingNotice: "Arrangement geändert; vorherige Betrachtung", readingError: "Fehler beim Erstellen. Bitte erneut versuchen.",
    gallery: "Galerie", galleryTitle: "Blumengalerie", gallerySubtitle: "Entdecken Sie Sträuße aus aller Welt.", latest: "Neueste", popular: "Beliebteste", likeAction: "Gefällt mir", likedAction: "Gefällt mir", visibilityLabel: "Öffentlich", publicBadge: "Öffentlich", privateBadge: "Privat", setPublic: "Öffentlich machen", setPrivate: "Privat machen", galleryNotice: "Fertige Sträuße erscheinen automatisch in der Galerie", galleryNoticePrivate: "Derzeit privat (nur für dich sichtbar)", anonymousFlorist: "Anonymer Blumenfreund", view3dBouquet: "3D-Strauß ansehen", remixCreation: "Als Vorlage nutzen", myCreations: "Meine Werke", noCreations: "Noch keine Werke vorhanden.", saveToGallery: "In Galerie speichern", savingToGallery: "Wird gespeichert…", savedToGallery: "In Galerie aufgenommen", retrySave: "Erneut versuchen", loadMore: "Mehr laden", loadingMore: "Wird geladen…", allLoaded: "Alle Werke geladen", emptyGallery: "Die Galerie ist noch leer. Teile deinen ersten Strauß!", confirmDeleteCreation: "Dieses Werk löschen?", visibilityUpdated: "Sichtbarkeit aktualisiert", creationDeleted: "Werk gelöscht",
    backdropNames: { linen: "Leinen", limestone: "Kalkstein", charcoal: "Anthrazit", forest: "Waldgrün" },
    vaseNames: { classic: "Sanfte Keramik", bud: "Kleine Vase", bowl: "Weite Schale", footed: "Fußurne", mug: "Teetasse", paper: "Papierhülle", canvas: "Papier und Band", naked: "Lose gebundene Stiele" },
    vaseNotes: { classic: "Runde Atelier-Vase", bud: "Schmale, ruhige Silhouette", bowl: "Niedrig und großzügig", footed: "Ein Hauch von Festlichkeit", mug: "Ein Gefäß für jeden Tag", paper: "Warm gefaltetes Kraftpapier", canvas: "Gefaltetes Papier mit Schleife", naked: "Einfach gebundene Stiele" },
    presets: { "first-light": "Erstes Licht", "meadow-air": "Wiesenluft", "cloud-study": "Wolkenstudie" },
    flowerNames: { rose: "Gartenrose", tulip: "Tulpe", daisy: "Gänseblümchen", poppy: "Klatschmohn", peony: "Pfingstrose", "blue-poppy": "Blauer Scheinmohn", eucalyptus: "Silberdollar-Eukalyptus", gerbera: "Gerbera", chrysanthemum: "Chrysantheme", hydrangea: "Hortensie", "lily-of-the-valley": "Maiglöckchen", fern: "Farn", "seeded-eucalyptus": "Eukalyptuszweig", sunflower: "Sonnenblume", orchid: "Orchidee", "calla-lily": "Calla", carnation: "Nelke", lily: "Lilie", lotus: "Lotosblume", anemone: "Anemone", chamomile: "Kamille", delphinium: "Rittersporn", snowdrop: "Schneeglöckchen", lavender: "Lavendel", ivy: "Efeu", monstera: "Monstera-Blatt", "ranunculus": "Ranunkel", "narcissus": "Narzisse", "dahlia": "Dahlie", "amaryllis": "Amaryllis", "astrantia": "Sterndolde", "eryngium": "Edeldistel", "pine-cone": "Kiefernzapfen" },
    colors: { "Dusty rose": "Altrosa", "Velvet red": "Samtrot", "Ivory cream": "Elfenbein", "Butter yellow": "Buttergelb", Apricot: "Aprikose", Mauve: "Mauve", Blush: "Zartrosa", "Tulip red": "Tulpenrot", "Golden yellow": "Goldgelb", White: "Weiß", Violet: "Violett", "Cream white": "Cremeweiß", "Golden daisy": "Goldgelb", Coral: "Koralle", Scarlet: "Scharlachrot", Orange: "Orange", "Blush pink": "Zartrosa", "Deep red": "Dunkelrot", "Himalayan blue": "Himalaya-Blau", "Violet blue": "Blauviolett", "Warm orange": "Warmorange", Red: "Rot", Pink: "Rosa", Yellow: "Gelb", Golden: "Goldgelb", Lavender: "Lavendel", "Misty lilac": "Flieder", "Garden blue": "Gartenblau", "Rose pink": "Rosenrosa", Ivory: "Elfenbein", "Soft pink": "Zartrosa", Terracotta: "Terrakotta", "Lemon cream": "Zitronencreme", "Blush mauve": "Altviolett", "Pure white": "Reinweiß", "Deep violet": "Dunkelviolett", "Snow white": "Schneeweiß", Sunshine: "Sonnengelb", "Dark plum": "Dunkle Pflaume", "Stargazer pink": "Rosa", "Tiger orange": "Tigerorange", "Deep rose": "Dunkelrosa", "Cornflower blue": "Kornblumenblau", "Classic purple": "Klassisches Violett", "Rose lavender": "Rosenlavendel", "White spike": "Weiße Blüte", "Bronze red": "Bronzerot", Butter: "Buttergelb", "Cobalt blue": "Kobaltblau", Crimson: "Karmesinrot", "Ivory peach": "Elfenbein-Pfirsich", "Violet purple": "Violett", Kraft: "Kraftpapier", Pearl: "Perlmutt", Stone: "Stein", Sage: "Salbei", Forest: "Waldgrün", Porcelain: "Porzellan", Charcoal: "Anthrazit" }, categoryName: { main: "Hauptblumen", filler: "Beiwerk", foliage: "Grün" },
  },
  fr: {
    language: "Langue", loading: "Préparation des fleurs…", brand: "Atelier floral numérique", stems: "tiges", undo: "Annuler", redo: "Rétablir", startOver: "Recommencer", finish: "Terminer le bouquet", waves: "Vagues", breeze: "Brise", rain: "Pluie", birds: "Oiseaux", fireplace: "Feu de cheminée", cicadas: "Cigales",
    step: "01 · Choisir · Placer · Créer", headline: "Composez dans l’espace.", intro: "Cliquez pour placer une fleur harmonieusement ou faites-la glisser pour ajuster sa position.",
    flowers: "Fleurs", containers: "Contenants", library: "Fleurs et contenants", main: "Fleurs principales", accents: "Fleurs d’accent", foliage: "Feuillages", chooseFlowers: "Qu’allez-vous composer aujourd’hui ?", chooseFlowersHint: "Choisissez une fleur et placez-la dans votre composition.", chooseContainer: "Choisir un contenant", chooseContainerHint: "Choisissez un vase, un emballage ou une composition inspirante.",
    added: "Ajouté", preorder: "sur commande", studioOnly: "inspiration", vase: "Vases", bouquets: "Bouquets emballés", imagination: "Inspirations", adjustContainer: "Ajuster le contenant", containerSize: "Taille du contenant", containerColor: "Couleur du contenant", opacity: "Opacité", stemsTab: "tiges", stem: "tige", adjust: "Ajuster les fleurs", adjustHint: "Cliquez sur une fleur pour modifier sa hauteur, sa taille, son angle et sa couleur.", tools: "Outils", tapToAdjust: "Ajouté. Touchez une fleur pour la modifier.", stemToAdjust: "Fleur à ajuster", stemHeight: "Hauteur de la tige", flowerSize: "Taille de la fleur", leafSize: "Taille du feuillage", lean: "Inclinaison", flowerColor: "Couleur de la fleur", removeStem: "Retirer cette tige", done: "Terminer l’ajustement",
    morningLight: "Lumière du matin", warmth: "Chaleur", balanced: "Équilibrée", cool: "Froide", warm: "Chaude", direction: "Direction", turnLeft: "À gauche", turnRight: "À droite", wind: "Vent", windStrength: "Force du vent", ambience: "Ambiance sonore", volume: "Volume", mute: "Couper le son", unmute: "Réactiver le son", rotateVase: "Faire pivoter le vase", rotateHint: "Glissez à gauche/droite pour tourner, en haut/bas pour incliner. Maintenez Maj pour rouler.", rotateTouchHint: "Balayez l’espace libre pour tourner et incliner. Utilisez le curseur ci-dessous pour basculer.", tilt: "Incliner", turn: "Tourner", roll: "Rouler", resetRotation: "Réinitialiser la vue", placeHint: "Choisissez une fleur puis cliquez dans l’espace pour la placer.", placePrompt: "Choisissez une fleur pour commencer", dragPrompt: "Faites glisser une fleur dans l’espace · Échap pour annuler",
    sendEyebrow: "Un bouquet à offrir", sendTitle: "Offrez votre bouquet.", sendHint: "Écrivez un mot et créez une carte personnelle à partager.", to: "À", message: "Message", from: "De", recipientPlaceholder: "Une personne chère", messagePlaceholder: "Que chaque jour vous apporte une fleur.", senderPlaceholder: "Votre nom", privateLink: "Lien privé de votre carte", copyLink: "Copier le lien", shareDirectly: "Partager", download: "Télécharger la carte", saveToPhotos: "Enregistrer dans Photos", longPressToSave: "Maintenez la carte appuyée, puis choisissez « Enregistrer l’image ».", createLink: "Créer le lien de partage", createAnother: "Créer un autre lien", creating: "Création…", back: "Retour à l’atelier", postcardTitle: "Bloomroom · Un bouquet à offrir", defaultMessage: "Que chaque jour vous apporte une fleur.", close: "Retour à l’atelier", credits: "Crédits des modèles 3D", postcardKicker: "Une petite attention pour vous", openBouquet: "Voir ce bouquet dans l’atelier", createBouquet: "Créer son propre bouquet",
    restored: "Bouquet restauré depuis le lien partagé.", full: "Votre composition contient 24 tiges. Retirez-en une pour continuer.", loadingModels: "Certains modèles 3D se chargent encore. Réessayez dans un instant.", addFirst: "Ajoutez d’abord une tige à votre composition.", captureError: "Impossible de capturer le bouquet. Veuillez réessayer.", saved: "Lien de la carte copié.", shareFallback: "Le partage n’est pas disponible ici ; le lien a été copié.", copyError: "Échec de la copie. Sélectionnez le lien ci-dessus pour le copier manuellement.", savingError: "Impossible d’enregistrer cette carte. Veuillez réessayer.", imageLoading: "L’image est en cours de rendu. Réessayez.", drawError: "Impossible de créer la carte. Veuillez réessayer.", countLabel: "tiges", of: "/", toName: "À", fromName: "De", backdrop: "Arrière-plan",
    login: "Connexion", signup: "S’inscrire", logout: "Déconnexion", myGarden: "Mon jardin", saveDraft: "Enregistrer brouillon", savingDraft: "Enregistrement…", draftSaved: "Brouillon enregistré", draftUpdated: "Brouillon mis à jour", drafts: "Brouillons", sentPostcards: "Cartes envoyées", noDrafts: "Aucun brouillon pour l’instant. Composez un bouquet pour commencer.", noSentPostcards: "Aucune carte envoyée pour l’instant.", continueEdit: "Continuer l’édition", remixCopy: "Créer une nouvelle copie", rename: "Renommer", deleteAction: "Supprimer", confirmDelete: "Supprimer ce brouillon ?", viewGift: "Voir la carte", authNotice: "Veuillez mémoriser votre nom d’utilisateur et votre mot de passe, la récupération n’est pas prise en charge.", loginToSaveHint: "Connectez-vous pour enregistrer ce brouillon. Notez vos identifiants (pas de récupération).", usernameLabel: "Nom d’utilisateur", passwordLabel: "Mot de passe", usernameHint: "3–32 lettres, chiffres ou tirets bas", passwordHint: "Votre mot de passe", confirmPasswordLabel: "Confirmer le mot de passe", confirmPasswordHint: "Saisissez à nouveau le mot de passe", passwordMismatch: "Les mots de passe ne correspondent pas", showPassword: "Afficher le mot de passe", hidePassword: "Masquer le mot de passe", alreadyHaveAccount: "Déjà un compte ? Connexion", needAccount: "Pas de compte ? S’inscrire", conflictNotice: "Ce brouillon a été modifié ailleurs. Enregistré comme nouvelle copie pour préserver votre travail.", untitledBouquet: "Bouquet sans titre", loginSuccess: "Connexion réussie", signupSuccess: "Compte créé et connecté", logoutSuccess: "Déconnexion réussie", draftLoaded: "Brouillon chargé dans l’atelier",
    loadBouquetError: "Impossible de charger ce bouquet. Réessayez ou repartez d’une carte déjà envoyée.",
    recordVoice: "Enregistrer un message vocal (optionnel)", recordingVoice: "Enregistrement en cours…", stopRecording: "Arrêter", rerecordVoice: "Réenregistrer", deleteVoice: "Supprimer la voix", playVoice: "Écouter", pauseVoice: "Pause", listenToVoice: "Écouter son message vocal", micDenied: "Impossible d’accéder au micro. Vérifiez les autorisations ou envoyez sans audio.", micUnsupported: "L’enregistrement audio n’est pas pris en charge sur cet appareil.", audioTooLarge: "Le fichier audio dépasse 2 Mo, veuillez réenregistrer.", audioPlayError: "Impossible de charger le message vocal.", voiceHint: "Jusqu’à 30 secondes, avec écoute et réenregistrement.",
    aiReading: "Reflet Floral", aiReadingHint: "Lisez un reflet de cet instant à travers la posture et la couleur.", aiReadingDisclaimer: "Réflexion psychologique créative", generateReading: "Générer la lecture", generatingReading: "Observation attentive du bouquet…", readingTitle: "Titre", readingComposition: "Composition", readingReflection: "Résonance", readingBody: "Lecture", readingPunchline: "Chute", readingQuote: "Devise florale", copyReading: "Copier le texte", readingCopied: "Texte copié dans le presse-papiers", saveReadingCard: "Enregistrer la carte", savingReadingCard: "Enregistrement…", regenerateReading: "Réinterpréter", outdatedReadingNotice: "Le bouquet a changé ; lecture précédente", readingError: "Échec de la génération. Veuillez réessayer.",
    gallery: "Galerie", galleryTitle: "Galerie Florale", gallerySubtitle: "Découvrez les bouquets créés à travers le monde.", latest: "Récents", popular: "Plus aimés", likeAction: "J’aime", likedAction: "Aimé", visibilityLabel: "Public", publicBadge: "Public", privateBadge: "Privé", setPublic: "Rendre public", setPrivate: "Rendre privé", galleryNotice: "Les bouquets terminés apparaissent automatiquement dans la galerie", galleryNoticePrivate: "Actuellement privé (visible uniquement par vous)", anonymousFlorist: "Fleuriste anonyme", view3dBouquet: "Voir le bouquet 3D", remixCreation: "Créer une copie", myCreations: "Mes œuvres", noCreations: "Aucune œuvre pour l’instant.", saveToGallery: "Enregistrer dans la galerie", savingToGallery: "Enregistrement…", savedToGallery: "Œuvre ajoutée à la galerie", retrySave: "Réessayer", loadMore: "Charger plus", loadingMore: "Chargement…", allLoaded: "Toutes les œuvres sont chargées", emptyGallery: "La galerie est vide. Partagez votre premier bouquet !", confirmDeleteCreation: "Supprimer cette œuvre ?", visibilityUpdated: "Visibilité mise à jour", creationDeleted: "Œuvre supprimée",
    backdropNames: { linen: "Lin", limestone: "Calcaire", charcoal: "Fusain", forest: "Forêt" },
    vaseNames: { classic: "Céramique douce", bud: "Vase soliflore", bowl: "Vasque large", footed: "Vase sur pied", mug: "Tasse à thé", paper: "Papier kraft", canvas: "Papier et ruban", naked: "Tiges simplement liées" },
    vaseNotes: { classic: "Vase d’atelier arrondi", bud: "Silhouette fine et discrète", bowl: "Bas et généreux", footed: "Une touche cérémonieuse", mug: "Un contenant du quotidien", paper: "Papier kraft plié", canvas: "Papier plié noué d’un ruban", naked: "Tiges nues simplement liées" },
    presets: { "first-light": "Première lumière", "meadow-air": "Brise des prés", "cloud-study": "Étude nuageuse" },
    flowerNames: { rose: "Rose de jardin", tulip: "Tulipe", daisy: "Marguerite", poppy: "Coquelicot", peony: "Pivoine", "blue-poppy": "Pavot bleu", eucalyptus: "Eucalyptus à feuilles rondes", gerbera: "Gerbera", chrysanthemum: "Chrysanthème", hydrangea: "Hortensia", "lily-of-the-valley": "Muguet", fern: "Fougère", "seeded-eucalyptus": "Branche d’eucalyptus", sunflower: "Tournesol", orchid: "Orchidée", "calla-lily": "Arum", carnation: "Œillet", lily: "Lis", lotus: "Lotus", anemone: "Anémone", chamomile: "Camomille", delphinium: "Pied-d’alouette", snowdrop: "Perce-neige", lavender: "Lavande", ivy: "Brin de lierre", monstera: "Feuille de monstera", "ranunculus": "Renoncule", "narcissus": "Narcisse", "dahlia": "Dahlia", "amaryllis": "Amaryllis", "astrantia": "Astrance", "eryngium": "Panicaut", "pine-cone": "Pomme de pin" },
    colors: { "Dusty rose": "Rose poudré", "Velvet red": "Rouge velours", "Ivory cream": "Crème ivoire", "Butter yellow": "Jaune beurre", Apricot: "Abricot", Mauve: "Mauve", Blush: "Rose pâle", "Tulip red": "Rouge tulipe", "Golden yellow": "Jaune doré", White: "Blanc", Violet: "Violet", "Cream white": "Blanc crème", "Golden daisy": "Marguerite dorée", Coral: "Corail", Scarlet: "Écarlate", Orange: "Orange", "Blush pink": "Rose tendre", "Deep red": "Rouge profond", "Himalayan blue": "Bleu de l’Himalaya", "Violet blue": "Bleu violacé", "Warm orange": "Orange chaud", Red: "Rouge", Pink: "Rose", Yellow: "Jaune", Golden: "Doré", Lavender: "Lavande", "Misty lilac": "Lilas brumeux", "Garden blue": "Bleu jardin", "Rose pink": "Rose", Ivory: "Ivoire", "Soft pink": "Rose doux", Terracotta: "Terre cuite", "Lemon cream": "Crème citron", "Blush mauve": "Mauve poudré", "Pure white": "Blanc pur", "Deep violet": "Violet profond", "Snow white": "Blanc neige", Sunshine: "Jaune soleil", "Dark plum": "Prune foncé", "Stargazer pink": "Rose Stargazer", "Tiger orange": "Orange tigré", "Deep rose": "Rose profond", "Cornflower blue": "Bleu bleuet", "Classic purple": "Violet classique", "Rose lavender": "Lavande rosée", "White spike": "Épi blanc", "Bronze red": "Rouge bronze", Butter: "Beurre", "Cobalt blue": "Bleu cobalt", Crimson: "Cramoisi", "Ivory peach": "Pêche ivoire", "Violet purple": "Violet", Kraft: "Kraft", Pearl: "Nacré", Stone: "Pierre", Sage: "Vert sauge", Forest: "Vert forêt", Porcelain: "Porcelaine", Charcoal: "Charbon" }, categoryName: { main: "Fleurs principales", filler: "Fleurs d’accent", foliage: "Feuillages" },
  },
} as const;

export type TranslationKey = keyof typeof copy.en;
export function t(language: Language, key: Exclude<TranslationKey, "vaseNames" | "vaseNotes" | "presets" | "flowerNames" | "colors" | "categoryName" | "backdropNames">): string {
  return copy[language][key] as string;
}

export function backdropName(language: Language, id: "linen" | "limestone" | "charcoal" | "forest") {
  return copy[language].backdropNames[id];
}

export function flowerName(language: Language, kind: keyof typeof copy.en.flowerNames) {
  return copy[language].flowerNames[kind] ?? copy.en.flowerNames[kind];
}
export function vesselName(language: Language, kind: keyof typeof copy.en.vaseNames) { return copy[language].vaseNames[kind]; }
export function vesselNote(language: Language, kind: keyof typeof copy.en.vaseNotes) { return copy[language].vaseNotes[kind]; }
export function presetName(language: Language, id: keyof typeof copy.en.presets) { return copy[language].presets[id]; }
export function presetNote(language: Language, id: keyof typeof copy.en.presets) {
  const stems = id === "first-light" ? ["rose", "tulip", "eucalyptus"] as const
    : id === "meadow-air" ? ["gerbera", "poppy", "fern"] as const
      : ["hydrangea", "chrysanthemum"] as const;
  return stems.map((kind) => flowerName(language, kind)).join(" · ");
}
export function categoryName(language: Language, category: keyof typeof copy.en.categoryName) { return copy[language].categoryName[category]; }
export function soundName(language: Language, id: "waves" | "wind" | "breeze" | "rain" | "birds" | "fireplace" | "cicadas") { return copy[language][id === "wind" ? "breeze" : id]; }
export function colorName(language: Language, english: string) {
  return (copy[language].colors as Record<string, string>)[english] ?? english;
}

